name: Auto Backend Snapshot

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Generate backend snapshot
        run: python snapshot_generator_backend.py

      - name: Commit and push snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update backend snapshot [skip ci]"
          branch: main
